### ISSUE TITLE
on-collapse-open event

### ISSUE THREAD

**Issue by eximius313** [PolymerElements/iron-collapse#14]
Could you please restore ```on-collapse-open``` event from 0.5 version of this component?
Thank you in advance

**Comment by yesobo** [comment]
You could listen for the 'transitionend' event and check the 'opened' attribute to know if opened or closed

**Comment by notwaldorf** [comment]
@eximius313 @yesobo `opened` is a notify property, so you can also listen to the `opened-changed` event as well. (and `event.detail.value` will be true or false accordingly). I think that's basically the same as `on-collapse-open`.

**Comment by eximius313** [comment]
It is not the same thing.
```opened-changed``` is fired immediately when the value has been changed even though iron-collapse has not fully opened.
on the contrary ```on-collapse-open``` serves exactly this purpose - is being fired only if core-collapse was fully opened.
Try to put google-map in iron collapse for example. If not ```on-collapse-open``` map will not work...

**Comment by morficus** [comment]
@eximius313 not sure if you found a solution to your problem or not, but the comment from @yesobo works perfectly. The `transitionend` event doesn't get fired until AFTER the element is fully expanded or collapsed. 

Here is some sample code.

```javascript
this.listen(collapseEl, 'transitionend', 'adjustLayout');
```

```javascript
function: adjustLayout(event) {
  if (event.target.opened) {
     // do some stuff
   } else {
     // do some other stuff
   }
}
```

**Comment by eximius313** [comment]
Thanks @morficus - I'll try it

**Comment by eximius313** [comment]
@morficus - it worked as expected. Thank you

**Comment by morficus** [comment]
:tada:
