### ISSUE TITLE
Horizontal open from right to left?

### ISSUE THREAD

**Issue by CragVFX** [PolymerElements/iron-collapse#16]
Is there a way to make the iron-collapse open from right to left when using horizontal? It seems that it either opens top to down without horizontal, and then left to right with horizontal..

**Comment by valdrinkoshi** [comment]
@CragVFX have you considered floating `iron-collapse` to right?
```css
iron-collapse {
  float: right;
}
```
Here an example http://jsbin.com/zokabocica/edit?html,css,output
