### ISSUE TITLE
enableTransition(false) has no effect

### ISSUE THREAD

**Issue by sklobovskaya** [PolymerElements/iron-collapse#20]
The element continues to animate open and closed after calling `enableTransition(false)`.

It looks like [_openChanged() internally enables and disables transitions using this same method](https://github.com/PolymerElements/iron-collapse/blob/master/iron-collapse.html#L166), and thus any previous enableTransition() setting is clobbered, as it is not persisted anywhere else beyond the transitionDuration style property.

**Comment by valdrinkoshi** [comment]
We could have either fix `enableTransition()` to actually enable/disable animations, or have a new property `animated` and make `enableTransition()` private (so it would be possible to disable animations declaratively). @notwaldorf what do you think?
