### ISSUE TITLE
Setting "horizontal" after element initialization breaks it

### ISSUE THREAD

**Issue by zoechi** [PolymerElements/iron-collapse#33]
I tried to rebuild the demo in Dart Angular2 and the `#collapse2` doesn't resize when  `#collapse3` is opened.
I could reproduce this in the JS demo when I initially remove the `horizontal` attribute from `#collapse3` and then add it just before I expand it.
This way it has an redundant `height: 0px;` which breaks the demo.
It seems for the initial default "vertial" dimension the "height: 0px" is added but then when switched to "horizontal" it is not removed.

Looks like when using the element with Angular, the timing is somehow different which results in this behavior.

**Comment by valdrinkoshi** [comment]
Hi @zoechi, this seems related to the fact that the old dimension doesn't get updated on horizontal changes. I've provided a fix for this in #41, currently under review

**Comment by zoechi** [comment]
Great!
