### ISSUE TITLE
Cannot set "opened" attribute to "false"

### ISSUE THREAD

**Issue by dplassgit** [PolymerElements/iron-collapse#36]
If you set the opened attribute to anything, it is interpreted as true.

e.g., 

`
<iron-collapse id="collapse" opened="false">
  inside collapse
</iron-collapse>
`

Still shows the content inside the collapse.

**Comment by valdrinkoshi** [comment]
Yes, as per [documentation](https://www.polymer-project.org/1.0/docs/devguide/properties.html#attribute-deserialization):
> Boolean properties are set based on the presence of the attribute: if the attribute exists at all, the property is set to true, regardless of the attribute value. If the attribute is absent, the property gets its default value.
