### ISSUE TITLE
iron-collapse has vertical scrollbar during animation

### ISSUE THREAD

**Issue by jarvima** [PolymerElements/iron-collapse#40]
iron-collapse has a vertical scrollbar that only displays during its animation.

The effect can be seen here https://elements.polymer-project.org/elements/iron-collapse?view=demo:demo/index.html

**Comment by jarvima** [comment]
One solution could be to add `this.style.overflow = 'hidden'` to `updateSize` and to add `this.style.overflow = 'auto'` to `_transitionEnd`.

**Comment by jarvima** [comment]
[This jsbin](https://jsbin.com/baqomodoku/3/edit?html,output) has a working example with the fix.

**Comment by mgiuffrida** [comment]
This also fixes an issue where the iron-collapse has too much height at the end of its animation if it contains text that wraps. Could someone please push an update?

**Comment by valdrinkoshi** [comment]
@mgiuffrida just released the `v1.0.6`
