### ISSUE TITLE
Element not registered in `$` if inside a DOM-IF template

### ISSUE THREAD

**Issue by OmriAharon** [PolymerElements/iron-collapse#46]
I had this structure:

```
    <template is="dom-if" if="{{...}}">
      <button on-click="toggle">Text</button>

      <iron-collapse id="myid">
        <div>Test</div>
      </iron-collapse>

    </template>

     ....

      toggle() {
        this.$.myid.toggle();
      }

     
```

And when I clicked the button which triggered the toggle function, I noticed that "myid" was not present in `this.$`. Only after placing the `iron-collapse` element outside of the if template did this work.

Is this by design?

**Comment by cdata** [comment]
Hi, this is a limitation of `dom-if`. Sorry! If you need it to be registered on `$`, then you should consider a different strategy to hide it.
