### ISSUE TITLE
animation doesn't work with padding

### ISSUE THREAD

**Issue by J3remyD** [PolymerElements/iron-collapse#47]
I'm trying to use an animated iron-collapse with a padding-bottom on it, basically on toggle, the animation takes the padding into account and does a strange expand effect, which doesn't occur when noAnimation is set to true

**Comment by valdrinkoshi** [comment]
Could you please share a jsbin showing the issue?

**Comment by J3remyD** [comment]
Hey, 
I was unable to reproduce it on JSbin (maybe because it's only Polymer 0.3.3).
Anyway if you go to the official Polymer element catalog -> [iron-collapses](https://elements.polymer-project.org/elements/iron-collapse?view=demo:demo/index.html&active=iron-collapse)
You just add a padding-bottom let's say 20px to the element-style of the iron-collapse id="collapse1" and try to open close you will see the weird unsmooth effect I'm talking about.

Please find the screenshot of the source modified:

![screen shot 2016-02-17 at 10 06 20](https://cloud.githubusercontent.com/assets/13484476/13104562/30aade76-d55e-11e5-9afb-966866fa6ccc.png)

And the gif as weel since .mov aren't supported:
![iron-collapse-weird-effect](https://cloud.githubusercontent.com/assets/13484476/13104839/e9a3359e-d55f-11e5-8e10-c81e644e5ca5.gif)

I hope it's more clear now.

Thanks,
Jeremy

**Comment by valdrinkoshi** [comment]
As explained in the [documentation](https://elements.polymer-project.org/elements/iron-collapse):
> iron-collapse adjusts the height/width of the collapsible element to show/hide the content. So avoid putting padding/margin/border on the collapsible directly, and instead put a div inside and style that.
