### ISSUE TITLE
this.offsetHeight is a read only property

### ISSUE THREAD

**Issue by jay8t6** [PolymerElements/iron-collapse#58]
The following line in iron-collapse.html is causing an error (stated below):

Line 204: iron-collapse.html
this.offsetHeight = this.offsetHeight

Error:
Uncaught TypeError: Cannot set property offsetHeight of #&lt;HTMLElement&gt; which has only a getter

Note that I am running the code through a transpiler because I have es6 code in my project.

Can you fix this?

**Comment by valdrinkoshi** [comment]
@jay8t6 fix released in `v1.1.1`

**Comment by jay8t6** [comment]
Great, thanks!
