### ISSUE TITLE
Anyway to change duration of the animation transition ?

### ISSUE THREAD

**Issue by RoXuS** [PolymerElements/iron-collapse#61]
### Description
The animation transition duration is static.

### Expected outcome
The animation transition duration should be configurable.

### Actual outcome
The animation transition duration is setted to 300ms.

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

Maybe it is not a good thing...

**Comment by luksak** [comment]
How can I change this property? Using CSS or a attribute on the iron-collapse elements?

**Comment by RoXuS** [comment]
Hello @luksak by using this mixin `--iron-collapse-transition-duration`

**Comment by luksak** [comment]
@RoXuS sorry, probably I am not familiar enough how style scoping of Polymer works in general. I tried doing this in an external stylesheet:

```iron-collapse {
  --iron-collapse-transition-duration: 10000ms;
}```

What am I doing wrong?
