### ISSUE TITLE
content of opened iron-collapse not shown

### ISSUE THREAD

**Issue by beta-vulgaris** [PolymerElements/iron-collapse#64]
### Description
An empty iron-collapse that gets opened won't show content loaded at a later time.

### Expected outcome
iron-collapse should show dynamically loaded content if opened

### Actual outcome
iron-collapse does not show anything (max-height: 0px)

### Live Demo
https://jsbin.com/jekeyotiko/edit?html,output

### Steps to reproduce

1. Put a `iron-collapse` element in the page, opened with no content.
2. Once the page is loaded, close and open (".toggle()") the empty 'iron-collapse'.
3. Load content into the 'iron-collapse' (".innerHTML =...")
4. The content won't show.

**Comment by valdrinkoshi** [comment]
You could also call `collapse1.updateSize('auto')` right after changing the `innerHTML`, but it's true that `iron-collapse` remains in a weird state if its content is empty
