### ISSUE TITLE
FeatureRequest: iron-collapse "opened" event

### ISSUE THREAD

**Issue by eximius313** [PolymerElements/iron-collapse#67]
### Description

Please provide possibility of listening to "opened" and "closed" events
### Expected outcome

Event is called when animation is finished

**Comment by valdrinkoshi** [comment]
Hi @eximius313, you could leverage the `iron-resize` event that is fired as soon as the opening/closing is done http://jsbin.com/fosohi/1/edit?html,console,output

**Comment by eximius313** [comment]
The problem is that ```iron-resize``` is also called for example every time I click inside an input field (which is inside my iron-collapse) even though it's already opened

**Comment by valdrinkoshi** [comment]
Oh true, that happens because `iron-collapse` keeps listening at `transitionend` events, and `paper-input` animation triggers one of those...As a consequence it also fires an unnecessary `iron-resize`, which is a bug.

**Comment by eximius313** [comment]
@valdrinkoshi 
Do you have any idea when your bugfix is merged?
