### ISSUE TITLE
Can't scroll after toggle on iOS 10.1.1

### ISSUE THREAD

**Issue by jagge1988** [PolymerElements/iron-collapse#70]
### Description
If the page doesn't had enough content that it must scroll than after a toggle of the iron collapse it isn't possible to scroll.

### Expected outcome
You can scroll to see all content.

### Actual outcome
No Scrolling possible

### Live Demo
https://elements.polymer-project.org/elements/iron-collapse?view=demo:demo/index.html&active=iron-collapse

### Steps to reproduce
1. Use an iPhone 
2. Go to the demo page of the iron-collapse. The content must not use all of the screen (use link above) 
3. Toggle the iron-collapse the get all the content. The content must use all of the screen
4. Try to scroll 

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Safari for iOS
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment]
Hi @jagge1988, I confirm that in the embedded demo page we cannot scroll the content, but in the actual demo page ([here](https://elements.polymer-project.org/bower_components/iron-collapse/demo/index.html)) scrolling works.
The same bug is present also in https://beta.webcomponents.org/element/PolymerElements/iron-collapse/demo/demo/index.html
I'll close this issue, I've opened new ones in the respective repos  https://github.com/Polymer/polymer-element-catalog/issues/293 and https://github.com/webcomponents/beta/issues/647
