### ISSUE TITLE
paper-menu not migrated to v2

### ISSUE THREAD

**Issue by fmatuszewski** [PolymerElements/iron-collapse#76]
### Description
paper-menu isn't migrated to polymer 2
### Expected outcome

when i type in console
bower install paper-menu#2.0-preview
it should be installed

### Actual outcome

bower paper-menu#2.0-preview     ENORESTARGET Tag/branch 2.0-preview does not exist
indeed there is no tag

### Steps to reproduce

bower install paper-menu#2.0-preview

### Browsers Affected

- [ +] Chrome
- [ +] Firefox
- [ +] Safari 9
- [ +] Safari 8
- [ +] Safari 7
- [ +] Edge
- [ +] IE 11
- [ +] IE 10

**Comment by valdrinkoshi** [comment]
wrong repository, anyways `<paper-menu>` has been deprecated in favor of `<paper-listbox>`.
https://github.com/googlearchive/paper-menu/
